### ISSUE TITLE
seafile proxy conf 

### ISSUE THREAD

**Issue by orkahmrust** [linuxserver/reverse-proxy-confs#101]
I've been trying to create a subdomain proxy config that will work with the official seafile docker file given at https://download.seafile.com/d/320e8adf90fa43ad8fee/files/?p=/docker/docker-compose.yml and can only get connection errors. Has anyone gotten these to work together?

**Comment by nemchik** [comment]
You'll need to either add your letsencrypt container to the custom network in that compose, or add those containers to a user defined network you're already using with other containers.

**Comment by orkahmrust** [comment]
Yeah, I've got it running on the same docker bridge as letsencrypt.

**Comment by nemchik** [comment]
You should be able to copy an existing proxy, for example adguard, and replace the name of the app everywhere you see it in the file.

**Comment by orkahmrust** [comment]
That's what I've done that is giving me ERR_CONNECTION_REFUSED whenever I try to access it.

**Comment by j0nnymoe** [comment]
> That's what I've done that is giving me ERR_CONNECTION_REFUSED whenever I try to access it.

You haven't given it the correct port in the proxy conf.

**Comment by tedcook94** [comment]
I'm still struggling with this. For my Seafile container, I mapped 8000:80, since I already have my letsencrypt container listening on 80. I'm able to access the Seafile Web UI by going to http://<server's local IP>:8000. But when I copy a subdomain conf and edit it like @nemchik suggested and restart the letsencrypt container, going to https://seafile.mydomain.com gives me a "Bad Request - Contradictory scheme headers" page. 

I was able to get past that error by changing the protocol in the subdomain.conf from http to https, but then I get a "Bad Gateway" error page. 

I can /bin/bash into my letsencrypt container and confirm that seafile:80 is open to it, so I'm not sure why I'm still getting a "Bad Gateway". My theory is that it has something to do with the fact that https and port 80 don't mix well together (though https and port 443 also give the same error), or that the nginx instance included in the seafile image is interfering somehow. But networking is not my strong suit, so any help is appreciated.

**Comment by tedcook94** [comment]
Ok, I managed to figure this out. I'm going to submit a PR to add a subdomain config, but I'll describe how I fixed it in case my PR is rejected and someone else has this same problem.

As @nemchik suggested, copy another config sample (I used adguard) and edit any app references with your container's name (so in my case adguard -> seafile). Then, replace the $upstream_port to 443 and the $upstream_proto to https. Restart your letsencrypt container to load your changes.

For your Seafile container, make sure you set the "SEAFILE_SERVER_LETSENCRYPT" environment variable to true and set "SEAFILE_SERVER_HOSTNAME" to seafile.yourdomain.com. Then restart the Seafile container, and you should be able to access the Seafile UI at https://seafile.yourdomain.com. I was also able to sync via a desktop client using the same URL.

**Comment by nemchik** [comment]
Closed in #162
