### ISSUE TITLE
organizr subfolder - location blocks in default

### ISSUE THREAD

**Issue by drizuid** [linuxserver/reverse-proxy-confs#168]
https://canary.discordapp.com/channels/354974912613449730/506925392603512839/715034647490199623

basically, user had commented out the location block but got a 404 in organizr until they also commented out the second location block. Once they commented that out, it worked fine. Since i do not use organizr I can't confirm something else wasn't at play. 

if this is true, we should add a note in the top of organizr.subfolder.conf.sample to inform users that they need to comment out the second location as well. 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by nemchik** [comment]
I can confirm, I would advise commenting out everything you listed here https://github.com/linuxserver/docker-letsencrypt/blob/03d22abb960b5c09f3a4f9b5f4920e288a9ba0a8/root/defaults/default#L35-L44
Otherwise an alternative would be to compartmentalize the php block into an include file that would be included in other configs. I may have brought up that idea and discussed it with @aptalca in the past. Anyway I'm in agreement with additional comments in the organizr proxy file.
