### ISSUE TITLE
Grafana LDAP?

### ISSUE THREAD

**Issue by lloydpick** [linuxserver/reverse-proxy-confs#60]
Trying to enable LDAP for Grafana subdomain, but I think I'm ending up in some weird loop. Might be because `/login` is also used by Grafana?

I have LDAP working correctly for other containers, so it's just this one misbehaving.

**Comment by aptalca** [comment]
If there is a clash due to login, try the steps below.

1) You can change the directive in your location block from `error_page 401 =200 /login;` to something like `error_page 401 =200 /ldaplogin;`
2) Copy the ldap.conf to a new file like ldap2.conf, reference that in the include statement of the server block. 
3) Edit the ldap2.conf and change the line `location /login {` to `location /ldaplogin {`

I haven't tested it, but it should work

**Comment by aptalca** [comment]
haven't heard back, closing

**Comment by jt70471** [comment]
Hi, I tried this, unfortunately it still doesn't work. Instead of being directed to the ldap-auth login page, I get a result that just says: Hello, world! Requested URL: /ldaplogin

Here's my updated grafana.subdomain.conf:

server {
    listen 443 ssl;
#   listen [::]:443 ssl;

    server_name grafana.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    include /config/nginx/ldap.conf;
    include /config/nginx/ldap2.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        auth_request /auth;
        error_page 401 =200 /ldaplogin;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s ipv6=off;
        set $upstream_grafana [redacted];
        proxy_pass http://$upstream_grafana:3000;
    }
}

And the new location I added to ldap2.conf:

location /ldaplogin {
        resolver 127.0.0.11 valid=30s ipv6=off;
        set $upstream_ldap [redacted];
        proxy_pass http://$upstream_ldap:9001;
        proxy_set_header X-Target $request_uri;
    }

**Comment by lloydpick** [comment]
Yeah, apologies for not updating the issue. This currently can't be done (as of when I last tested maybe a week or so ago), because in the ldap-auth container, the path is hard coded to be `/login` at the following places. There might be more, I've not spent much time looking.

https://github.com/linuxserver/docker-ldap-auth/blob/master/root/app/ldap-backend-app.py#L30

https://github.com/linuxserver/docker-ldap-auth/blob/master/root/app/ldap-backend-app.py#L75
