### ISSUE TITLE
[FEAT] tubearchivist proxy conf

### ISSUE THREAD

**Issue by binarygeek119** [linuxserver/reverse-proxy-confs#703]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

i need help and would like to have you guys add tubearchivist to the proxy confs
https://github.com/tubearchivist/tubearchivist

### Reason for change

its missing

### Proposed code change

im not sure what need to be done here.

**Comment by drizuid** [comment]
HI, I suggest starting with our template we provide then adapt the settings to tubearchivist. Once it's working fully, feel free to PR your change to us. It's hacktoberfest, so if you get it in during october (and signed up) you'll get credit. Otherwise, unless another user submits one, it wont happen. most confs here are contributed by the users of the applications.

**Comment by n00b12345** [comment]
Would really appreciate some help in this regard. I started with a template but I'm unable to get it to work.

**Comment by j0nnymoe** [comment]
> Would really appreciate some help in this regard. I started with a template but I'm unable to get it to work.

Already replied to yourself on the forum.

**Comment by drizuid** [comment]
closing this as confs are user submitted and this conversation belongs in discord or the forums.
